### ISSUE TITLE
Implement a soft/silent arming feature

### ISSUE THREAD

**Issue by zaid** [Tokenize/evl-daemon-elixir#7]
It would be great if there was a way to not arm the system but make it so that we will get alerted if zones have activity without notifying the monitoring centre.

We will need to specify which zones we are interested in as well as which events to get notified on (using priorities probably).

**Comment by zaid** [comment]
@mfarr any ideas on how we should do this? Should we specify which zones we will monitor when someone POSTs to our API? Or should we have some pre-set profiles and we specify which profile to use when we POST to the API? so maybe one of these two options:

1- Specify which zones to arm/bypass in the JSON payload:
  ```
{
   bypassed_zones: [1, 5, 7],
   armed_zones: [2, 3, 4]
  }
```

2- Have profiles defined on the server (using config files / JSON / YAML) then specify the profile name:
   ```
{
    soft_arm: {
        profile: "All doors without motion sensors"
    }
}
```

**Comment by mfarr** [comment]
I think option 1 makes the most sense. The flexibility will allow clients to define their own zones/profiles rather than using only server-specified profiles.

**Comment by zaid** [comment]
So I was thinking, when the option to silent arm the system is enabled, we would do this:

  - Register a new event listener (a type of notifier?) which receives events of all priorities.
  - If an event code matches a Zone open (609) then dispatch an event with a matching high priority so for example, it would be a Zone Alarm (601)
  - If an event to arm the system is detected then we disable silent arming.

Does that make sense?

**Comment by zaid** [comment]
Added support for both create & destroy actions so that you can do the following to create a new task
```
curl --verbose -X POST -H Content-Type:application/json -d "{\"type\":\"silent_arm\", \"zones\":\"[1,5]\"}" http://127.0.0.1:4000/tasks\?auth_token\=SECRET
```

And the following to delete the task
```
curl --verbose -X DELETE -H Content-Type:application/json -d "{\"type\":\"silent_arm\", \"zones\":[\"001\",\"005\"]}" http://127.0.0.1:4000/tasks\?auth_token\=SECRET
```

A couple of notes on the API's response:
  - Attempting to create a **silent_arm** task twice will cause the second call to fail with 422 error.
  - Attempting to delete a non-existant task will fail with 422 error.

**Comment by zaid** [comment]
Ran into a few bugs such as passing in string hash keys instead of atoms...etc.
